name: Split Packages
on:
  push:
    branches:
      - main
      - '0.*'
    tags:
      - '*'
jobs:
  tag_split_payments:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ['opayo','stripe']
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          coverage: none

      - name: Split ${{ matrix.package }}
        uses: "symplify/monorepo-split-github-action@2.3"
        if: "!startsWith(github.ref, 'refs/tags/')"
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          package_directory: 'payment/${{ matrix.package }}'
          repository_organization: 'lunarphp'
          repository_name: '${{ matrix.package }}'
          user_name: "GitHub Action"
          user_email: "action@github.com"
          branch: ${GITHUB_REF#refs/heads/}

      - name: Set env
        if: "startsWith(github.ref, 'refs/tags/')"
        run: echo "GITHUB_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Split ${{ matrix.package }}
        uses: "symplify/monorepo-split-github-action@2.3"
        if: "startsWith(github.ref, 'refs/tags/')"
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          package_directory: 'payment/${{ matrix.package }}'
          repository_organization: 'lunarphp'
          repository_name: '${{ matrix.package }}'
          user_name: "GitHub Action"
          user_email: "action@github.com"
          branch: ${GITHUB_TAG%.*}

      - name: Tag ${{ matrix.package }}
        if: "startsWith(github.ref, 'refs/tags/')"
        uses: "symplify/monorepo-split-github-action@2.3"
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          tag: ${GITHUB_REF#refs/tags/}
          package_directory: 'payment/${{ matrix.package }}'
          repository_organization: 'lunarphp'
          repository_name: '${{ matrix.package }}'
          user_name: "GitHub Action"
          user_email: "action@github.com"
          branch: ${GITHUB_TAG%.*}

  tag_split_search:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ['meilisearch']
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          coverage: none

      - name: Split ${{ matrix.package }}
        uses: "symplify/monorepo-split-github-action@2.3"
        if: "!startsWith(github.ref, 'refs/tags/')"
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          package_directory: 'search/${{ matrix.package }}'
          repository_organization: 'lunarphp'
          repository_name: '${{ matrix.package }}'
          user_name: "GitHub Action"
          user_email: "action@github.com"
          branch: ${GITHUB_REF#refs/heads/}

      - name: Set env
        if: "startsWith(github.ref, 'refs/tags/')"
        run: echo "GITHUB_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Split ${{ matrix.package }}
        uses: "symplify/monorepo-split-github-action@2.3"
        if: "startsWith(github.ref, 'refs/tags/')"
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          package_directory: 'search/${{ matrix.package }}'
          repository_organization: 'lunarphp'
          repository_name: '${{ matrix.package }}'
          user_name: "GitHub Action"
          user_email: "action@github.com"
          branch: ${GITHUB_TAG%.*}

      - name: Tag ${{ matrix.package }}
        if: "startsWith(github.ref, 'refs/tags/')"
        uses: "symplify/monorepo-split-github-action@2.3"
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          tag: ${GITHUB_REF#refs/tags/}
          package_directory: 'search/${{ matrix.package }}'
          repository_organization: 'lunarphp'
          repository_name: '${{ matrix.package }}'
          user_name: "GitHub Action"
          user_email: "action@github.com"
          branch: ${GITHUB_TAG%.*}
