name: Split Packages
on:
  push:
    branches:
      - main
    tags:
      - '*'
jobs:
  tag_split_payments:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [
          'opayo',
          'stripe'
        ]
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          coverage: none
      - name: Split ${{ matrix.package }}
        uses: symplify/github-action-monorepo-split@main
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          package_directory: 'payment/${{ matrix.package }}'
          repository_organization: 'lunarphp'
          repository_name: '${{ matrix.package }}'
          user_name: "GitHub Action"
          user_email: "action@github.com"
          branch: "main"

      - name: Tag ${{ matrix.package }}
        if: "startsWith(github.ref, 'refs/tags/')"
        uses: symplify/github-action-monorepo-split@main
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          tag: ${GITHUB_REF#refs/tags/}
          package_directory: 'payment/${{ matrix.package }}'
          repository_organization: 'lunarphp'
          repository_name: '${{ matrix.package }}'
          user_name: "GitHub Action"
          user_email: "action@github.com"
          branch: "main"
